# Default values for homer.

replicaCount: 1

image:
  repository: teslamate/teslamate
  pullPolicy: IfNotPresent
  tag: ""

ports: 
  sql:
    port: 4000

env:
  DATABASE_NAME: teslamate
  DATABASE_HOST: database
  MQTT_HOST: mosquitto

env_secret:
  DATABASE_USER: ""
  DATABASE_PASS:
  MQTT_USERNAME: ""
  MQTT_PASSWORD:

ingress:
  local:
    host:
    subdomain: teslamate.
    port: 4000