# Default values for homer.

replicaCount: 1

image:
  repository: linuxserver/duckdns
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  PUID: 1000
  PGID: 1000
  TZ: Europe/Berlin
  SUBDOMAINS: somedomain

env_secret:
  TOKEN: "" # Change this