replicaCount: 1

image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

bind: 
  data:
    mountPath: /config
    hostPath: /var/lib/home-assistant

env:
  TZ: Europe/Berlin

# Internal ports
ports: 
  http:
    port: 8123

# External access
ingress:
  local:
    host: ""                           # Change this
    subdomain: home.
    port: 8123  