namespace: kube-system
replicaCount: 1

# Docker Image
image:
  repository: traefik
  pullPolicy: IfNotPresent
  tag: ""

# Available entrypoints
entryPoints:
  web:
    port: 80
    protocol: TCP
  websecure:
    port: 443
    protocol: TCP

# External IP
hostIP: 

# External url {prefix}{host}
ingress:  # Change this
  host:
  prefix: traefik.

# DuckDNS configuration, set empty string "" to remove 
duckdns:            
  secretName: duckdns-token
  caServer: https://acme-staging-v02.api.letsencrypt.org/directory
  email: some.one@mail.com
  token: ""
  certPath: /var/lib/traefik/cert