replicaCount: 1

#Docker image
image:
  repository: grafana/grafana
  pullPolicy: IfNotPresent
  tag: ""

# Data storage 
bind: 
  data:
    mountPath: /var/lib/grafana
    hostPath: /var/lib/grafana

# Internal ports
ports: 
  http:
    port: 3000

# Ingress
ingress:
  local:
    host: ""                           # Change this
    subdomain: grafana.
    port: 3000