# Default values for homer.

replicaCount: 1

#Docker image for MinIO
image:
  repository: grafana/grafana
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Main Data storage location
bind: 
  data:
    mountPath: /var/lib/grafana
    hostPath: /var/lib/grafana

# Internal port of Chronograf
ports: 
  http:
    port: 3000

# External access
ingress:
  local:
    host: ""                           # Change this
    subdomain: grafana.
    port: 3000