replicaCount: 1

image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

configFiles:
  plugins:
    mountPath: /etc/rabbitmq/enabled_plugins
    file: enabled_plugins

serviceSuffixInternal: -ui
serviceSuffixExternal: -broker

# Main Data storage location
bind: 
  data:
    mountPath: /var/lib/rabbitmq
    hostPath: /var/lib/rabbitmq

env_secret:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: WRuxr7q@iaZ@7_qNPQ6p2L.VjkfRH2dK2Kgsh_68j9 # change this

# Internal port
ports: 
  http:
    port: 15672

externalIP: #change this
externalPorts:
  mqtt:
    port: 1883

ingressTCP:
  endpoint: mqtt
  port: 1883

# External access
ingress:
  local:
    host: ""                           # Change this
    subdomain: rabbitmq.
    port: 15672

