{{- if .Values.duckdns -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.duckdns.secretName }}
  namespace: {{ .Values.namespace | default "kube-system" }}
type: "Opaque"
data:
  duckdns_token: {{ default "" .Values.duckdns.token | b64enc | quote }}
{{- end -}}