replicaCount: 1

image:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  tag: ""

bind: 
  data:
    mountPath: /data
    hostPath: /var/lib/node-red

env:
  TZ: Europe/Berlin

# Internal ports
ports: 
  http:
    port: 1880

# Ingress
ingress:
  local:
    host:
    subdomain: nodered.
    port: 1880  