replicaCount: 1

image:
  repository: nodered/node-red
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

bind: 
  data:
    mountPath: /data
    hostPath: /var/lib/node-red

env:
  TZ: Europe/Berlin

# Internal ports
ports: 
  http:
    port: 1880

# External access
ingress:
  local:
    host: ""                           # Change this
    subdomain: nodered.
    port: 1880  