---
{{- define "baseChart.ingressRoute.tpl" -}}

{{- if .Values.ingress.local -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "baseChart.name" . }}
spec:
  entryPoints:
    - web
  routes:
  - match: {{ printf "Host(`%s%s`)" .Values.ingress.local.subdomain .Values.ingress.local.host }}
    kind: Rule
    services:
    - name: {{ include "baseChart.name" . }}
      port: {{ .Values.ingress.local.port }}

{{- end }}{{/* if */}}

{{- if .Values.ingress.public }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "baseChart.name" . }}-public
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule

    {{- $host := printf "%s%s" ( .Values.ingress.public.subdomain | default "" ) .Values.ingress.public.host }}
    
    {{- if .Values.ingress.public.pathPrefix }}
    match: {{ printf "Host(`%s`) && PathPrefix(`/%s`)" $host .Values.ingress.public.pathPrefix }}
    {{- else }}
    match: {{ printf "Host(`%s`)" $host }}
    {{- end }}

    {{- if .Values.ingress.public.middlewares }}
    middlewares:
      {{- range .Values.ingress.public.middlewares }}
      - name: {{ .name }}
        namespace: {{ .namespace }}
      {{- end }}
    {{- end }}
    services:
    - name: {{ include "baseChart.name" . }}
      port: {{ .Values.ingress.public.port }}
  tls:
    certResolver: {{ .Values.ingress.public.certResolver }}
    {{- if .Values.ingress.public.sans }}
    domains:
    - main: {{ .Values.ingress.public.domain | default $host }}
      sans:
      {{- range .Values.ingress.public.sans }}
      - {{ . }}
      {{- end }}
    {{- end }}{{/* if */}}

  {{- end }}{{/* if */}}
  {{- end }}{{/* template */}}
