---
{{- define "baseChart.ingressRouteTCP.tpl" -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "baseChart.name" . }}

spec:
  entryPoints:
    - {{ .Values.ingressTCP.endpoint }}
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ include "baseChart.name" . }}
      port: {{ .Values.ingressTCP.port }}
      weight: 10
      terminationDelay: 400
      proxyProtocol:
        version: 1
{{- end }}