---
{{- define "baseChart.secrets.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baseChart.secretName" . }}
type: "Opaque"
data:
  {{- range $name, $value := .Values.env_secret }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}

{{- end }}