# Docker image
image:
  repository: registry.gitlab.com/arm-research/smarter/smarter-device-manager

resources:
  requests:
    cpu: 10m
    memory: 15Mi
  limits:
    cpu: 100m
    memory: 15Mi

# Enable configmap
configFiles:
  mappings:
    mountPath: /root/config

# Data storage
bind: 
  device-plugin:
    mountPath: /var/lib/kubelet/device-plugins
    hostPath: /var/lib/kubelet/device-plugins
    type: Directory
  dev-dir:
    mountPath: /dev
    hostPath: /dev
    type: Directory
  sys-dir:
    mountPath: /sys
    hostPath: /sys
    type: Directory

#deviceMappings:
#   Examples:
# - devicematch: ^ttyUSB[0-9]*$
#   nummaxdevices: 1
# - devicematch: ^ttyACM[0-9]*$
#   nummaxdevices: 1