replicaCount: 1
strategy: Recreate

#Docker image
image:
  repository: adguard/adguardhome
  pullPolicy: IfNotPresent
  tag: ""

# Networking
dnsPolicy: ClusterFirstWithHostNet
hostNetwork: true

# Data storage
bind: 
  config:
    mountPath: /opt/adguardhome/conf
    hostPath: /var/lib/adguard/config
  data:
    mountPath: /opt/adguardhome/work
    hostPath: /var/lib/adguard/data

# Internal ports
ports: 
  ui:
    port: 3000
    type: TCP
    
# Ingress
ingress:
  local:
    host:
    subdomain: adguard.
    port: 3000