# Default values for homer.

replicaCount: 1

#Docker image for MinIO
image:
  repository: minio/minio
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Startup arguments for MinIO
args: 
  - server 
  - /data

# Main Data storage location
bind: 
  data:
    mountPath: /data
    hostPath: /var/lib/minio/data

# Internal port of MinIO
ports: 
  http:
    port: 9000

# MinIO initial credentials (change this)
env_secret:
  MINIO_ACCESS_KEY: EgerzAUefgqDvApzG8kuYDB6V4paaoi*ARGgd-P*xn
  MINIO_SECRET_KEY: jcnGzhUc.x2xg.Kt*c*xMoYwXsN9kGpF*nnBkXU@6c

# External access
ingress:
  local:
    host: ""                           # Change this
    prefix: s3.
    port: 9000