replicaCount: 1

#Docker image
image:
  repository: minio/minio
  pullPolicy: IfNotPresent
  tag: ""

# Startup arguments
args: 
  - server 
  - /data

# Data storage
bind: 
  data:
    mountPath: /data
    hostPath: /var/lib/minio/data

# Internal ports
ports: 
  http:
    port: 9000

# Initial credentials
env_secret:
  MINIO_ACCESS_KEY:
  MINIO_SECRET_KEY:

# Ingress
ingress:
  local:
    host:
    subdomain: s3.
    port: 9000