replicaCount: 1

image:
  repository: linuxserver/syncthing
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  PUID: 1000
  PGID: 1000
  TZ: Europe/Berlin

bind: 
  config:
    mountPath: /config
    hostPath: /var/lib/syncthing/config

# Internal port
ports: 
  http:
    port: 8384
    type: TCP
  sync:
    port: 22000
    type: TCP
  syncudp:
    port: 21027
    type: UDP

# External access
ingress:
  local:
    host: ""                           # Change this
    subdomain: syncthing.
    port: 8384