# Default values for homer.

replicaCount: 1

#Docker image for MinIO
image:
  repository: chronograf
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Main Data storage location
bind: 
  data:
    mountPath: /var/lib/chronograf
    hostPath: /var/lib/influxdb/chronograf

# Internal port of Chronograf
ports: 
  http:
    port: 8888

# External access
ingress:
  local:
    host: ""                           # Change this
    subdomain: chronograf.
    port: 8888