replicaCount: 1

#Docker image
image:
  repository: chronograf
  pullPolicy: IfNotPresent
  tag: ""

# Data storage
bind: 
  data:
    mountPath: /var/lib/chronograf
    hostPath: /var/lib/influxdb/chronograf

# Internal ports
ports: 
  http:
    port: 8888

# Ingress
ingress:
  local:
    host: ""                           # Change this
    subdomain: chronograf.
    port: 8888