---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "baseChart.name" . }}-sync
  labels:
    {{- include "baseChart.labels" . | nindent 4 }}
spec:

  externalIPs: 
    - {{ .Values.externalIP }}
  type: ClusterIP

  {{- /* Ports the service is exposing in the cluster */}}
  ports:
    - name: sync
      port: {{ .Values.ports.sync.port }}
      targetPort: {{ .Values.ports.sync.port }}
      protocol: TCP
    - name: syncudp
      port: {{ .Values.ports.syncudp.port }}
      targetPort: {{ .Values.ports.syncudp.port }}
      protocol: UDP

  {{- /* Selectors to identify pods to forward to */}}
  selector:
    {{- include "baseChart.selectorLabels" . | nindent 4 }}
