replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: ""

# Internal ports
ports: 
  sql:
    port: 5432

env_secret:
  POSTGRES_PASSWORD: ""

# Data storage
bind: 
  data:
    mountPath: /var/lib/postgresql/data
    hostPath: /var/lib/postgresql/data