replicaCount: 1

#Docker image
image:
  repository: influxdb
  pullPolicy: IfNotPresent
  tag: ""

# Data storage
bind: 
  data:
    mountPath: /var/lib/influxdb
    hostPath: /var/lib/influxdb/data

# Internal ports
ports: 
  http:
    port: 8086

# Ingress
ingress:
  local:
    host: ""                           # Change this
    subdomain: influxdb.
    port: 8086